name: dynamics-modeling
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - scikit-learn
  - h5py
  - pytorch
  - torchvision
  - tqdm
  - ros-rosbag
