name: dynamics-modeling
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Current requirement for ros-roslz4
  - matplotlib
  - numpy
  - scikit-learn
  - h5py
  - pytorch
  - torchvision
  - tqdm
  - pyyaml
  - ros-rospy
  - ros-roslz4
  - pip
  - pip:
    - --extra-index-url https://rospypi.github.io/simple/
    # Messages
    - nav-msgs
    - geometry-msgs
    # rosbag that's cool with python 3.9, but apparently doesn't list dependencies, so these are appended to the end of this pip list
    - rosbag
    - rospkg
    - pycryptodomex
    - python-gnupg
