name: dynamics-modeling
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Current requirement for ros-roslz4
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  # Running task scripts
  - invoke=1.5.0
  # Linting
  - black>=22.3.0
  - flake8=3.9.2
  - isort=5.8.0
  - mypy=0.812
  - pip
  - pip:
    - --extra-index-url https://rospypi.github.io/simple/
    - -e .
    # Tensorboard
    - tensorboard
    - torch-tb-profiler
    # This is needed for script cleaning up tensorboard runs
    - tensorflow